### ISSUE TITLE
How can I reproduce your experiment?

### ISSUE THREAD

**Issue by taku-ito** [yangyiben/Conditional-N-gram-Regularization#1]
Hi!

I read your paper. It was an interesting paper.
Could you tell me the preprocessing and commands necessary to reproduce the experiment?

Thank you!

**Comment by yangyiben** [comment]
python main_fast.py --cuda  --tied --batch_size=64     --epochs=30
--ngram_bsz=500  --data=./data/1B2.5M --data_name=1B
--ngram_dir=bigram_ppl/  --gamma=0.75 --loss_type=comb

You will have build two python list objects under ngram_dir: 1. list of
n-1_grams ( you should map token to integer) 2.  list of sparse matrix (
(row, column, data) format) of corresponding conditional distribution of
n_th token conditioned on n-1_grams

**Comment by yangyiben** [comment]
It should be list of batches for both cases

**Comment by yangyiben** [comment]
It should be list of batches for both cases

**Comment by taku-ito** [comment]
Thanks! I'll try.
